# 使用官方 Node.js 18 镜像作为基础镜像
FROM docker.1ms.run/node:18-alpine
# 官方镜像拉不下来，先使用1ms的镜像
# FROM node:18-alpine


# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json 到工作目录
COPY package*.json ./

# 安装项目依赖
# RUN npm install
RUN npm install --production

# 复制项目文件到工作目录
COPY . .

# 构建 Next.js 项目
RUN npm run build

# 暴露端口
EXPOSE 3000

# 启动 Next.js 应用
CMD ["npm", "start"]    